# Generated by Django 4.1.7 on 2023-02-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_created_by_alter_sale_prod_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale_type',
        ),
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='SaleType',
        ),
    ]
