# Generated by Django 4.1.7 on 2023-02-25 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_sale_sale_type_alter_sale_name_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coupon',
            name='sale_coupon_slug_3195f7_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='slug',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['coupon_code'], name='sale_coupon_coupon__4d215a_idx'),
        ),
    ]
