# Generated by Django 4.1.7 on 2023-02-25 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0004_remove_coupon_sale_coupon_slug_3195f7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
