# Generated by Django 4.1.7 on 2023-02-25 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_company_id_alter_company_alias'),
        ('sale', '0005_alter_coupon_created_by'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productsale',
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='productsale',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comp_prod_sale', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsale',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='productsale',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productsale',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
