# Generated by Django 4.1.7 on 2023-02-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='compare',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='wish',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
