# Generated by Django 4.1.7 on 2023-02-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='account',
            name='_type',
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=15, verbose_name='Type'),
        ),
    ]
