# Generated by Django 4.1.7 on 2023-02-21 09:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename__type_contact_type_remove_account__type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='profile',
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], db_column='type', default='CUSTOMER', max_length=15, verbose_name='Type'),
        ),
        migrations.RenameField(
            model_name='account',
            old_name='type',
            new_name='_type',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type',
        ),
        migrations.AddField(
            model_name='contact',
            name='_type',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('EMAIL', 'Email'), ('SOCIAL_NET', 'Social net')], db_column='type', default='PHONE', max_length=15, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
