# Generated by Django 4.1.7 on 2023-03-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_address_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='is_default',
        ),
    ]
