# Generated by Django 4.1.7 on 2023-02-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_managers_remove_profile_is_valid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('-created_at',), 'permissions': [('view_dashboard', 'View page: Dashboard'), ('change_password', 'Change account password'), ('allow_chat', 'Allow chat')], 'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_at',), 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',), 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
