# Generated by Django 4.1.7 on 2023-03-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_address_address_line_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Instructions'),
        ),
    ]
