# Generated by Django 4.1.7 on 2023-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_ca_slug_6890c5_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='format: required, letters, numbers, underscore, or hyphens', max_length=150, verbose_name='Category URL'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['company_id', 'slug'], name='category_ca_company_b870c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_category_slug'),
        ),
    ]
