# Generated by Django 4.1.7 on 2023-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_icon_category_thumb_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='thumb_type',
        ),
        migrations.AddField(
            model_name='category',
            name='thumb_as',
            field=models.CharField(choices=[('IMG', 'Image'), ('SVG', 'Svg icon'), ('HIDDEN', 'Hidden')], default='IMG', max_length=15, verbose_name='Thumbnail as'),
        ),
    ]
