# Generated by Django 4.1.7 on 2023-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_thumb_type_category_thumb_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='thumb_as',
            field=models.CharField(choices=[('IMG', 'Image'), ('SVG', 'Svg icon'), ('HIDDEN', 'Hidden')], default='HIDDEN', max_length=15, verbose_name='Thumbnail as'),
        ),
    ]
