# Generated by Django 4.1.7 on 2023-02-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_thumb_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
