# Generated by Django 4.1.7 on 2023-02-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_icon_category_svg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='order',
            new_name='position',
        ),
    ]
