# Generated by Django 4.1.7 on 2023-03-01 15:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.JSONField(help_text='Required')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 999.99.'}}, help_text='Maximum 999.99', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000000)], verbose_name='delivery price')),
                ('method', models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], default='IS', help_text='Required', max_length=255, verbose_name='delivery_method')),
                ('time_frame', models.CharField(blank=True, help_text='Required', max_length=255, null=True, verbose_name='delivery timeframe')),
                ('time_window', models.CharField(blank=True, help_text='Required', max_length=255, null=True, verbose_name='delivery window')),
                ('position', models.IntegerField(default=0, help_text='Required', verbose_name='list order')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_deliveries', to='company.company')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
                'ordering': ['position'],
            },
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
    ]
