# Generated by Django 4.1.7 on 2023-03-01 15:53

from django.db import migrations, models
import django.db.models.manager
import django.utils.timezone
import ecomm.apps.company.models.company
import ecomm.vendors.mixins.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.CharField(max_length=30, unique=True)),
                ('name', models.JSONField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=ecomm.apps.company.models.company.company_logo_upload_to)),
                ('options', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, ecomm.vendors.mixins.model.CacheMixin),
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['alias'], name='company_com_alias_a4ab0f_idx'),
        ),
    ]
