# Generated by Django 4.1.7 on 2023-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
