# Generated by Django 4.1.7 on 2023-02-24 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import ecomm.apps.product.models.media


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_company_id_alter_company_alias'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=ecomm.apps.product.models.media.product_media_upload_to)),
                ('alt', models.JSONField(blank=True, max_length=80, null=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_media', to='company.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media', to='product.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
    ]
