# Generated by Django 4.1.7 on 2023-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_slug_6278ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='productattribute',
            name='product_pro_slug_a99d04_idx',
        ),
        migrations.RemoveIndex(
            model_name='productbase',
            name='product_pro_slug_aa13d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='producttype',
            name='product_pro_slug_0a3c49_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Product URL'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='slug',
            field=models.SlugField(max_length=180, verbose_name='Product(base) URL'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company_id', 'sku'], name='product_pro_company_7b3bda_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company_id', 'slug'], name='product_pro_company_026543_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['company_id', 'slug'], name='product_pro_company_c7ac48_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['company_id', 'slug'], name='product_pro_company_bacfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='producttype',
            index=models.Index(fields=['company_id', 'slug'], name='product_pro_company_f2bd3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company_id', 'sku'), name='unique_product_sku'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_product_slug'),
        ),
        migrations.AddConstraint(
            model_name='productattribute',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_attribute_slug'),
        ),
        migrations.AddConstraint(
            model_name='productbase',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_prod_base_slug'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('company_id', 'slug'), name='unique_prod_type_slug'),
        ),
    ]
