# Generated by Django 4.1.7 on 2023-02-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_options_company_id_alter_company_alias'),
        ('product', '0004_alter_productbase_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_media', to='company.company'),
        ),
    ]
